# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_contact', models.CharField(max_length=30)),
                ('activities', models.ManyToManyField(to='activities.Activity')),
            ],
        ),
    ]
